// Copyright Mantle Place. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"

/**
 * Pure (engine-/IO-free) logic for the local tile server: which on-disk file a request path names,
 * and how a served file is labelled to the client.
 *
 * Both decisions were made inline in FMantlePlaceLocalTileServer, where neither could be asserted:
 * the server needs an HTTP router, a bound port and a directory on disk, so a test of it is a test
 * nobody runs. What it decides, though, is exactly the kind of thing worth asserting — the path
 * resolution is a **containment check on an attacker-shaped input**, and it is the only thing
 * standing between a request path and the rest of the machine's filesystem.
 *
 * The split follows the rule in `unreal/CLAUDE.md`: the shim executes, the logic unit decides. What
 * stayed behind in the shim is exactly the impure half — does this file exist, read its bytes,
 * build the response.
 */
struct FMantlePlaceLocalTileServerLogic
{
	/**
	 * Resolve an HTTP request path to the absolute file path it names beneath `RootDirAbs`, or empty
	 * if it names nothing servable.
	 *
	 * `RootDirAbs` must already be absolute and normalised (the server does that once at Start).
	 * Pure: no filesystem access, so a non-empty result means "this path is inside the served root",
	 * NOT "this file exists" — the caller still has to ask.
	 *
	 * Empty is returned for: an empty path, the root itself, anything containing `..`, and anything
	 * whose resolved form leaves the served root. The `..` rule is deliberately cruder than the
	 * containment check that follows it, and refuses a legitimate file whose own name contains two
	 * dots. That trade is on purpose: the served tree is machine-generated by the pipeline
	 * (`{z}/{x}/{y}.terrain`, `layer.json`, `Imagery.png`), so nothing that should be served is lost,
	 * and a traversal that never reaches the path arithmetic cannot be let through by a mistake in it.
	 */
	static FString ResolveUnderRoot(const FString& RootDirAbs, const FString& RequestPath);

	/**
	 * The content type to serve `FilePath` as, setting `bOutGzip` when the file is gzip **on disk**
	 * and must be declared as such rather than compressed again.
	 *
	 * Only quantized-mesh tiles are: CTB writes `.terrain` gzipped, so the bytes go out verbatim
	 * with `Content-Encoding: gzip` and the client inflates them. Anything unrecognised is served as
	 * octet-stream rather than guessed at.
	 */
	static FString ContentTypeFor(const FString& FilePath, bool& bOutGzip);
};
